[[redirects]]
  from = "/success"
  to = "/?popup=success"
  status = 302
  force = true

[[redirects]]
  from = "/fail"
  to = "/?popup=fail"
  status = 302
  force = true

[[redirects]]
  from = "/result"
  to = "https://ufa.wpkormimpravilno.ru/wp-json/kormimpravilno/v1/result?OutSum=:outsum&InvId=:invid&SignatureValue=:signaturevalue&isTest=:istest"
  status = 302
  force = true
  query = {OutSum = ":outsum", InvId = ":invid", SignatureValue = ":signaturevalue", isTest=":istest"}