[[redirects]]
  from = "/success"
  to = "/?popup=success"
  status = 302
  force = true

[[redirects]]
  from = "/fail"
  to = "/?popup=fail"
  status = 302
  force = true

[[redirects]]
  from = "/success"
  to = "https://spb.wpkormimpravilno.ru/wp-json/kormimpravilno/v1/?OutSum=:outsum&InvId=:invid&SignatureValue=:signaturevalue"
  status = 302
  force = true
  query = {OutSum = ":outsum", InvId = ":invid", SignatureValue = ":signaturevalue"}